### ISSUE TITLE
[FEATURE REQUEST] Random playlist

### ISSUE THREAD

**Issue by Bestfast** [manuel-rw/jellyfin-discord-music-bot#126]
Would be cool to have a /play-random command or something like that, so you can play endlessly 24/7 like a radio (or well, until there are members in the voice channel)

**Describe the solution you'd like**
/random, play or whatever command to play 24/7 a random song, with /skip command to songs you dont want to listen to

 
I usually have music as a background while studying/playing etc so that would be very helpful. I don't think it should be hard to implement; in the worst possible scenario you could periodically pull a list of song in the server, but I think the API do actually have a better way to all this. At the end, most players supports it, so I think it would be a very nice addition

**Comment by manuel-rw** [comment]
Confirmed that this is indeed possible with the ``items-api``, as it has a ``sortBy`` of ``random``.

**Comment by manuel-rw** [comment]
Confirmed, that this can be done using the ``items-api`` of Jellyfin. The item type must be set to ``Audio``, limited, enabled with recursive searching and must have the ``sortBy`` ``random`` to retrieve random items. Since the proof of concept is now working, I will implement the ``/ranom`` command.

**Comment by manuel-rw** [comment]
Implemented in #130
